### ISSUE TITLE
Copy page feature fails

### ISSUE THREAD

**Issue by mrerichoffman** [event-catalog/eventcatalog#1714]
### I tried this:

When hosting event catalog in github pages or enabling the trailingSlash in eventcatalog.config.js, the copy page button shows "Copy failed" when clicked and the View as Markdown option navigates to a 404 page that ends with /.mdx. The functionality works fine in dev mode, but fails when deployed to GH pages.

### This happened:

<img width="546" height="101" alt="Image" src="https://github.com/user-attachments/assets/483d6a2b-afab-40e3-ab03-ffeae8eda5ae" />

<img width="907" height="483" alt="Image" src="https://github.com/user-attachments/assets/94f0d54f-c77f-41cb-9626-b8ea7e86a45e" />

### I expected this:

The copy page feature to not fail or navigate to a broken page.

### Is there a workaround?

No

### EventCatalog Version

2.56.2

### Node.js Version

22

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
Thanks @mrerichoffman , found the problem and fix will be out in the next patch of EventCatalog.

https://github.com/event-catalog/eventcatalog/pull/1718

Thanks for raising!

**Comment by boyney123** [comment]
@all-contributors add @mrerichoffman for bug

**Comment by mrerichoffman** [comment]
@boyney123 Can you reopen this bug? I see the change is fixed in dev mode when enabling the trailingSlash config for v2.56.3. But the deployed github page continues to fail when clicking the copy button. When I click view as markdown the GH page 404s as well:

With trailingSlash enabled:
/1.0.0.mdx/

<img width="776" height="608" alt="Image" src="https://github.com/user-attachments/assets/3279a0a2-19cf-4859-8b5a-79c9a7c5ae27" />

With trailingSlash disabled:
/1.0.0/.mdx

<img width="776" height="608" alt="Image" src="https://github.com/user-attachments/assets/e1cc6eeb-0c34-4588-a318-1d87b6e99ed7" />

**Comment by Vinceveve** [comment]
I'm still getting the bug on github page.

Fix is by generating an index.html page on a postbuild phase.

```js
import { readdirSync, statSync, mkdirSync, renameSync } from 'fs';
import { join, extname } from 'path';

const DIST = new URL('../dist', import.meta.url).pathname;

function convertToDirectory(filePath) {
  const tmp = filePath + '.__tmp__';
  renameSync(filePath, tmp);
  mkdirSync(filePath);
  renameSync(tmp, join(filePath, 'index.html'));
  console.log(`  ✓ ${filePath.replace(DIST, 'dist')}/index.html`);
}

function walkDocs(dir) {
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      walkDocs(fullPath);
    } else if (extname(entry) === '.mdx' || extname(entry) === '.md') {
      convertToDirectory(fullPath);
    }
  }
}

function walkGenerated(dir) {
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      walkGenerated(fullPath);
    } else if (extname(entry) !== '') {
      convertToDirectory(fullPath);
    }
  }
}

console.log('Post-build: converting API routes and schema files to directories…');
walkDocs(join(DIST, 'docs'));
walkGenerated(join(DIST, 'generated'));
console.log('Done.');
```
