### ISSUE TITLE
npm run build has error

### ISSUE THREAD

**Issue by jltnf54** [event-catalog/eventcatalog#648]
Running on windows:

after checking out project and running npm run build:

see the following error:

![image](https://github.com/user-attachments/assets/af3585b5-0686-4109-a652-b01633b35afb)

**Comment by boyney123** [comment]
Thank you for raising this. I believe we have fixed that now in `@eventcatalog/core@2.0.30` can you update and verify? thanks!

**Comment by boyney123** [comment]
If its still an issue please re-open the issue and tag us :),thanks!

**Comment by mattiasclaesson** [comment]
@boyney123 got the fix but it still fails, likely because cross-env was not added to package.json?

$ npm run dev

> lynkco-event-catalog@0.1.0 dev
> eventcatalog dev

Setting up EventCatalog....
EventCatalog is starting at http://localhost:3000/docs
'cross-env' is not recognized as an internal or external command,
operable program or batch file.
node:child_process:965
    throw err;
    ^

Error: Command failed: cross-env PROJECT_DIR='C:\Users\40114616\lync-co\event-catalog-web-app\lynkco-event-catalog-sit' CATALOG_DIR='C:\Users\40114616\lync-co\event-catalog-web-app\lynkco-event-catalog-sit\.eventcatalog-core' npm run dev
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at _Command.<anonymous> (C:\Users\40114616\lync-co\event-catalog-web-app\lynkco-event-catalog-sit\node_modules\@eventcatalog\core\bin\dist\eventcatalog.cjs:3121:42)
    at _Command.listener [as _actionHandler] (C:\Users\40114616\lync-co\event-catalog-web-app\lynkco-event-catalog-sit\node_modules\@eventcatalog\core\bin\dist\eventcatalog.cjs:1443:21)
    at C:\Users\40114616\lync-co\event-catalog-web-app\lynkco-event-catalog-sit\node_modules\@eventcatalog\core\bin\dist\eventcatalog.cjs:2233:24
    at _Command._chainOrCall (C:\Users\40114616\lync-co\event-catalog-web-app\lynkco-event-catalog-sit\node_modules\@eventcatalog\core\bin\dist\eventcatalog.cjs:2141:16)
    at _Command._parseCommand (C:\Users\40114616\lync-co\event-catalog-web-app\lynkco-event-catalog-sit\node_modules\@eventcatalog\core\bin\dist\eventcatalog.cjs:2231:31)
    at C:\Users\40114616\lync-co\event-catalog-web-app\lynkco-event-catalog-sit\node_modules\@eventcatalog\core\bin\dist\eventcatalog.cjs:2042:31 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 73708,
  stdout: null,
  stderr: null
}

**Comment by mattiasclaesson** [comment]
Did solve it by installing cross-env globaly
npm install --global cross-env
Not sure this is the best way.

**Comment by carlosallexandre** [comment]
@mattiasclaesson,

`cross-env`  is at devDependencies. [Check here](https://github.com/event-catalog/eventcatalog/blob/main/package.json#L71)

**Comment by carlosallexandre** [comment]
@mattiasclaesson you are right. Thanks for note this.

I create a PR at `create-eventcatalog` for fix this.
Let's wait for @boyney123 review [it here](https://github.com/event-catalog/create-eventcatalog/pull/20)

**Comment by jturek-olx** [comment]
Hey, I believe this issue is still relevant. As someone mentioned above, it's in the `devDependencies` - shouldn't it be in `dependencies`? I don't think installing globally is a way to fix the problem
